spring:
  application:
    name: interface-control-center
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/icc}
    username: ${DB_USERNAME:icc}
    password: ${DB_PASSWORD:icc_local}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  error:
    include-message: never
